name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upgrade Cython
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
            distribution: 'temurin'
            java-version: "17"
   
         
      - name: Build with Buildozer
        run: |
          python -m pip install --upgrade buildozer Cython==0.29.33 virtualenv
          export PATH=$PATH:~/.local/bin/
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          cd ${{ github.workspace }}
          buildozer android debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
        #  path: ${{ steps.buildozer.outputs.filename }}